module.exports = {
  edit: {
    image1: { node: "3", field: "image", upload: true },
    sampler_name: { node: "4", field: "sampler_name" },
    seed: { node: "7", field: "noise_seed" },
    unet_name: { node: "8", field: "unet_name" },
    clip_name: { node: "9", field: "clip_name" },
    prompt: { node: "10", field: "text" },
    negative_prompt: { node: "11", field: "text" },
    vae_name: { node: "12", field: "vae_name" },
    megapixels: { node: "16", field: "megapixels" },
    cfg: { node: "17", field: "cfg" },
    steps: { node: "18", field: "steps" },
    parent_metadata: { node: "30", field: "value" },
    
    lora1_name: { node: "24", field: "lora_name" },
    lora1_strength: { node: "24", field: "strength_model" },
    lora2_name: { node: "23", field: "lora_name" },
    lora2_strength: { node: "23", field: "strength_model" },
    lora3_name: { node: "22", field: "lora_name" },
    lora3_strength: { node: "22", field: "strength_model" },
    lora4_name: { node: "19", field: "lora_name" },
    lora4_strength: { node: "19", field: "strength_model" },
    lora5_name: { node: "20", field: "lora_name" },
    lora5_strength: { node: "20", field: "strength_model" },
    lora6_name: { node: "21", field: "lora_name" },
    lora6_strength: { node: "21", field: "strength_model" }
  },
  upscale: {
    image: { node: "16", field: "image", upload: true },
    parent_metadata: { node: "40", field: "value" },
    seed: { node: "10", field: "seed" },
    resolution: { node: "10", field: "resolution" },
    max_resolution: { node: "10", field: "max_resolution" },
    batch_size: { node: "10", field: "batch_size" },
    uniform_batch_size: { node: "10", field: "uniform_batch_size" },
    color_correction: { node: "10", field: "color_correction" },
    temporal_overlap: { node: "10", field: "temporal_overlap" },
    input_noise_scale: { node: "10", field: "input_noise_scale" },
    latent_noise_scale: { node: "10", field: "latent_noise_scale" },
    offload_device: { node: "10", field: "offload_device" },
    
    // SeedVR2LoadVAEModel (Node 13)
    device: { node: "13", field: "device" },
    encode_tiled: { node: "13", field: "encode_tiled" },
    encode_tile_size: { node: "13", field: "encode_tile_size" },
    encode_tile_overlap: { node: "13", field: "encode_tile_overlap" },
    decode_tiled: { node: "13", field: "decode_tiled" },
    decode_tile_size: { node: "13", field: "decode_tile_size" },
    decode_tile_overlap: { node: "13", field: "decode_tile_overlap" },
    
    // SeedVR2LoadDiTModel (Node 14)
    dit_model: { node: "14", field: "model" },
    dit_device: { node: "14", field: "device" },
    blocks_to_swap: { node: "14", field: "blocks_to_swap" },
    attention_mode: { node: "14", field: "attention_mode" }
  },
  gen1: {
    width: { node: "52", field: "width" },
    height: { node: "52", field: "height" },
    // The selected model feeds both loaders; the INT8 switch decides which one runs.
    unet_name: [
      { node: "54", field: "unet_name" },
      { node: "85", field: "unet_name" }
    ],
    use_int8_loader: { node: "86", field: "value" },
    int8_model_type: { node: "85", field: "model_type" },
    int8_enable_convrot: { node: "85", field: "enable_convrot" },
    vae_name: { node: "55", field: "vae_name" },
    clip_name: { node: "69", field: "clip_name" },
    seed: { node: "63", field: "seed" },
    steps: { node: "63", field: "steps" },
    cfg: { node: "63", field: "cfg" },
    denoise: { node: "63", field: "denoise" },
    sampler_name: { node: "63", field: "sampler_name" },
    scheduler: { node: "63", field: "scheduler" },
    prompt: { node: "72", field: "text" },
    use_image_input: { node: "83", field: "value" },
    megapixels: { node: "81", field: "megapixels" },
    image: { node: "80", field: "image", upload: true },
    lora1_name: { node: "64", field: "lora_name" },
    lora1_strength: { node: "64", field: "strength_model" },
    lora2_name: { node: "73", field: "lora_name" },
    lora2_strength: { node: "73", field: "strength_model" },
    lora3_name: { node: "74", field: "lora_name" },
    lora3_strength: { node: "74", field: "strength_model" },
    lora4_name: { node: "75", field: "lora_name" },
    lora4_strength: { node: "75", field: "strength_model" },
    lora5_name: { node: "76", field: "lora_name" },
    lora5_strength: { node: "76", field: "strength_model" },
    lora6_name: { node: "77", field: "lora_name" },
    lora6_strength: { node: "77", field: "strength_model" }
  },
  krea2_edit: {
    image: { node: "8", field: "image", upload: true },
    image_b: { node: "23", field: "image", upload: true },
    unet_name: { node: "16", field: "unet_name" },
    vae_name: { node: "5", field: "vae_name" },
    clip_name: { node: "1", field: "clip_name" },
    prompt: { node: "9", field: "prompt" },
    grounding_px: [
      { node: "9", field: "grounding_px" },
      { node: "7", field: "grounding_px" }
    ],
    // Sizing: node 30 switches between scaling off the input image (node 29)
    // and an aspect-ratio target (node 26 -> resize node 27).
    scale_to_ref: { node: "30", field: "value" },
    aspect_ratio: { node: "26", field: "aspect_ratio" },
    megapixels: [
      { node: "29", field: "megapixels" },
      { node: "26", field: "megapixels" },
      { node: "24", field: "megapixels" }
    ],
    resolution_multiple: [
      { node: "29", field: "resolution_steps" },
      { node: "26", field: "multiple" },
      { node: "24", field: "resolution_steps" }
    ],
    seed: { node: "11", field: "seed" },
    steps: { node: "11", field: "steps" },
    cfg: { node: "11", field: "cfg" },
    sampler_name: { node: "11", field: "sampler_name" },
    scheduler: { node: "11", field: "scheduler" },
    identity_lora_name: { node: "21", field: "lora_name" },
    identity_lora_strength: { node: "21", field: "strength_model" },
    ref_boost: { node: "34", field: "ref_boost" },
    fit_mode: { node: "34", field: "fit_mode" },
    lora1_name: { node: "12", field: "lora_name" },
    lora1_strength: { node: "12", field: "strength_model" },
    lora2_name: { node: "13", field: "lora_name" },
    lora2_strength: { node: "13", field: "strength_model" },
    lora3_name: { node: "14", field: "lora_name" },
    lora3_strength: { node: "14", field: "strength_model" },
    lora4_name: { node: "15", field: "lora_name" },
    lora4_strength: { node: "15", field: "strength_model" },
    lora5_name: { node: "17", field: "lora_name" },
    lora5_strength: { node: "17", field: "strength_model" },
    lora6_name: { node: "22", field: "lora_name" },
    lora6_strength: { node: "22", field: "strength_model" }
  },
  prompt_enhancer: {
    user_prompt: { node: "15", field: "value" },
    system_prompt: { node: "13", field: "value" },
    enable_enhancer: { node: "7", field: "value" },
    use_image_ref: { node: "8", field: "value" },
    llm_clip_name: { node: "10", field: "clip_name" },
    image: { node: "2", field: "image", upload: true },
    max_length: { node: "18", field: "max_length" },
    temperature: { node: "18", field: "sampling_mode.temperature" },
    top_k: { node: "18", field: "sampling_mode.top_k" },
    top_p: { node: "18", field: "sampling_mode.top_p" },
    repetition_penalty: { node: "18", field: "sampling_mode.repetition_penalty" }
  }
};
